# configure_env.ps1 - write backend\.env for an offline production install.
#   -DbPassword  PostgreSQL superuser password (same value passed to init_postgres)
#   -JwtSecret   strong random secret for JWT signing
param(
    [Parameter(Mandatory = $true)][string]$DbPassword,
    [Parameter(Mandatory = $true)][string]$JwtSecret
)

. "$PSScriptRoot\common.ps1"

$envPath = Join-Path $BackendDir '.env'

# Single-origin deployment: nginx serves the UI and reverse-proxies the API, so
# the browser only ever talks to http://localhost:$NginxPort.
$origins = "http://localhost:$NginxPort,http://127.0.0.1:$NginxPort"

# Forward slashes so the values are unambiguous in .env / Python on Windows.
$appData = $AppDataDir -replace '\\', '/'

$content = @"
# Generated by the Attendance Platform installer - do not edit by hand.
APP_NAME=Attendance Platform
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost:$NginxPort

CORS_ALLOW_ORIGINS=$origins

# --- Database (portable PostgreSQL service installed locally) ---
DB_HOST=127.0.0.1
DB_PORT=$PgPort
DB_DATABASE=$DbName
DB_USERNAME=$DbUser
DB_PASSWORD=$DbPassword

# --- Redis + Celery (local services installed by the bootstrap) ---
# Redis backs cross-worker rate limiting / duplicate suppression / realtime
# pub-sub. Celery worker + beat (run by the tray launcher) handle periodic jobs.
REDIS_ENABLED=true
REDIS_URL=redis://127.0.0.1:$RedisPort/0
CELERY_ENABLED=true
# Broker + result backend default to REDIS_URL when unset.

# --- JWT ---
JWT_SECRET=$JwtSecret
JWT_ALGORITHM=HS256
JWT_EXPIRATION_MINUTES=1440

# --- AI / Recognition (models bundled offline) ---
ANTISPOOF_ENABLED=true
ANTISPOOF_MODEL_PATH=models/MiniFASNetV2.onnx
LIVENESS_ENABLED=true

# Writable runtime data lives under ProgramData (the install dir under Program
# Files is read-only for the non-elevated launcher).
INDEX_PATH=$appData/faiss.index
METADATA_PATH=$appData/metadata.json
VISITOR_UPLOAD_DIR=$appData/uploads
ENGINE_SNAPSHOT_DIR=$appData/snapshots/unknown
"@

Write-Log "Writing backend .env ..."
Set-Content -Path $envPath -Value $content -Encoding utf8
Write-Log "Wrote $envPath"
