"""initial_schema

Revision ID: 50fa64e85121
Revises: 
Create Date: 2026-06-03 00:12:35.078216
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50fa64e85121'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('notifiable_type', sa.String(length=255), nullable=False),
    sa.Column('notifiable_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_notifiable_type_notifiable_id', 'notifications', ['notifiable_type', 'notifiable_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=255), server_default='UTC', nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokenable_type', sa.String(length=255), nullable=False),
    sa.Column('tokenable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('abilities', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_personal_access_tokens_tokenable', 'personal_access_tokens', ['tokenable_type', 'tokenable_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('attendance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grace_minutes', sa.SmallInteger(), server_default='15', nullable=False),
    sa.Column('min_work_minutes', sa.SmallInteger(), server_default='240', nullable=False),
    sa.Column('max_work_minutes', sa.SmallInteger(), server_default='600', nullable=False),
    sa.Column('break_minutes', sa.SmallInteger(), server_default='60', nullable=False),
    sa.Column('overtime_after_minutes', sa.SmallInteger(), server_default='480', nullable=False),
    sa.Column('overtime_multiplier', sa.Numeric(precision=4, scale=2), server_default='1.5', nullable=False),
    sa.Column('night_shift_start', sa.Time(), nullable=True),
    sa.Column('night_shift_end', sa.Time(), nullable=True),
    sa.Column('night_shift_multiplier', sa.Numeric(precision=4, scale=2), server_default='1.25', nullable=False),
    sa.Column('weekend_days', sa.JSON(), nullable=True),
    sa.Column('weekend_multiplier', sa.Numeric(precision=4, scale=2), server_default='1.5', nullable=False),
    sa.Column('holiday_paid', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('auto_checkout_exit_zone', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('require_liveness_checkin', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('min_confidence', sa.Numeric(precision=5, scale=4), server_default='0.95', nullable=False),
    sa.Column('half_day_minutes', sa.SmallInteger(), server_default='240', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=255), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=255), server_default='UTC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('attendance_policy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), server_default='fixed', nullable=False),
    sa.Column('rotation_slot', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('grace_minutes', sa.SmallInteger(), server_default='15', nullable=False),
    sa.Column('break_minutes', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('min_work_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('max_work_minutes', sa.SmallInteger(), nullable=True),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attendance_policy_id'], ['attendance_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building_connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('driver', sa.Enum('webhook', 'mqtt', 'bacnet_gateway', name='connectordriver'), server_default='webhook', nullable=False),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('subscribed_events', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('camera_type', sa.String(length=32), server_default='rtsp', nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('stream_url', sa.String(length=255), nullable=True),
    sa.Column('target_fps', sa.SmallInteger(), nullable=True),
    sa.Column('resolution_width', sa.SmallInteger(), nullable=True),
    sa.Column('resolution_height', sa.SmallInteger(), nullable=True),
    sa.Column('direction', sa.Enum('in', 'out', 'both', name='cameradirection'), server_default='both', nullable=False),
    sa.Column('deployment_mode', sa.Enum('cloud', 'edge', name='deploymentmode'), server_default='cloud', nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'maintenance', name='camerastatus'), server_default='active', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frame_rate_fps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('bandwidth_kbps', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), server_default='0', nullable=False),
    sa.Column('health_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_code', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('face_enrolled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('face_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index('ix_employees_organization_id_is_active', 'employees', ['organization_id', 'is_active'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', 'location_id')
    )
    op.create_table('rfid_readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', 'both', name='rfiddirection'), server_default='both', nullable=False),
    sa.Column('api_token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), server_default='local', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=255), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('remember_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_provider', 'oauth_id')
    )
    op.create_index('ix_users_auth_provider_external_id', 'users', ['auth_provider', 'external_id'], unique=False)
    op.create_table('access_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('door', 'turnstile', 'gate', name='devicetype'), server_default='door', nullable=False),
    sa.Column('default_action', sa.Enum('unlock_door', 'lock_door', 'open_turnstile', 'open_gate', name='defaultaction'), server_default='unlock_door', nullable=False),
    sa.Column('controller_url', sa.String(length=255), nullable=True),
    sa.Column('require_liveness', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('min_confidence', sa.Numeric(precision=5, scale=4), server_default='0.95', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_method', sa.String(length=255), nullable=True),
    sa.Column('check_out_method', sa.String(length=255), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='absent', nullable=False),
    sa.Column('attendance_type', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date')
    )
    op.create_index('ix_attendance_records_work_date_status', 'attendance_records', ['work_date', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('building_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_connector_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'skipped', name='buildingeventstatus'), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['building_connector_id'], ['building_connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_building_events_building_connector_id_created_at', 'building_events', ['building_connector_id', 'created_at'], unique=False)
    op.create_table('camera_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('frame_rate_fps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('bandwidth_kbps', sa.Integer(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gpu_usage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dropped_frames', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recognition_events', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_camera_health_logs_camera_id_recorded_at', 'camera_health_logs', ['camera_id', 'recorded_at'], unique=False)
    op.create_table('edge_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=64), nullable=False),
    sa.Column('stream_url', sa.String(length=255), nullable=True),
    sa.Column('local_ai_url', sa.String(length=255), server_default='http://127.0.0.1:8001', nullable=False),
    sa.Column('status', sa.Enum('pending', 'online', 'offline', 'error', name='edgedevicestatus'), server_default='pending', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('poll_interval_seconds', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('require_liveness', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('recognition_threshold', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sync_version', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frame_rate_fps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('software_version', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('camera_id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('face_enrollment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.SmallInteger(), nullable=False),
    sa.Column('average_quality_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('enrollment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('enrollment_mode', sa.String(length=32), server_default='structured', nullable=False),
    sa.Column('raw_images_retained', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='leavestatus'), server_default='pending', nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognition_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('matched', 'unknown', 'liveness_failed', 'low_confidence', name='recognitionresult'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('liveness_passed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('image_hash', sa.String(length=255), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recognized_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recognition_events_recognized_at_result', 'recognition_events', ['recognized_at', 'result'], unique=False)
    op.create_table('rfid_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_index('ix_rfid_cards_uid_is_active', 'rfid_cards', ['uid', 'is_active'], unique=False)
    op.create_table('rfid_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_reader_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=False),
    sa.Column('result', sa.Enum('matched', 'unknown', 'inactive', 'duplicate_ignored', name='rfideventresult'), server_default='unknown', nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('tapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rfid_reader_id'], ['rfid_readers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rfid_events_employee_id_tapped_at', 'rfid_events', ['employee_id', 'tapped_at'], unique=False)
    op.create_index('ix_rfid_events_tapped_at_result', 'rfid_events', ['tapped_at', 'result'], unique=False)
    op.create_table('role_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('flex_start_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_assignments_employee_id_effective_from', 'shift_assignments', ['employee_id', 'effective_from'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('host_employee_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('check_in_code', sa.String(length=12), nullable=True),
    sa.Column('badge_number', sa.String(length=32), nullable=True),
    sa.Column('visit_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'checked_in', 'expired', 'cancelled', name='visitorstatus'), server_default='scheduled', nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('face_registered', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ai_identity_id', sa.String(length=255), nullable=True),
    sa.Column('face_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['host_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_in_code')
    )
    op.create_index('ix_visitors_status_face_expires_at', 'visitors', ['status', 'face_expires_at'], unique=False)
    op.create_table('access_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_point_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deny_reason', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('liveness_passed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_events_access_point_id_occurred_at', 'access_events', ['access_point_id', 'occurred_at'], unique=False)
    op.create_table('attendance_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_record_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='anomalyseverity'), server_default='medium', nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), server_default='0', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', 'false_positive', name='anomalystatus'), server_default='open', nullable=False),
    sa.Column('detection_run_id', sa.String(length=36), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_anomalies_anomaly_type_status', 'attendance_anomalies', ['anomaly_type', 'status'], unique=False)
    op.create_index('ix_attendance_anomalies_employee_id_detected_at', 'attendance_anomalies', ['employee_id', 'detected_at'], unique=False)
    op.create_index('ix_attendance_anomalies_status_severity', 'attendance_anomalies', ['status', 'severity'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('face_enrollment_session_id', sa.Integer(), nullable=True),
    sa.Column('faiss_id', sa.String(length=255), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('image_index', sa.SmallInteger(), nullable=True),
    sa.Column('pose_type', sa.String(length=32), nullable=True),
    sa.Column('face_metadata', sa.JSON(), nullable=True),
    sa.Column('version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['face_enrollment_session_id'], ['face_enrollment_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faiss_id')
    )
    op.create_table('face_enrollment_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('face_enrollment_session_id', sa.Integer(), nullable=False),
    sa.Column('image_index', sa.SmallInteger(), nullable=False),
    sa.Column('pose_type', sa.String(length=32), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('validation_checks', sa.JSON(), nullable=True),
    sa.Column('face_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['face_enrollment_session_id'], ['face_enrollment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('access_point_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_live_events_occurred_at_event_type', 'live_events', ['occurred_at', 'event_type'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), server_default='medium', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='alertstatus'), server_default='open', nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('recognition_event_id', sa.Integer(), nullable=True),
    sa.Column('access_point_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recognition_event_id'], ['recognition_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_alerts_alert_type_severity', 'security_alerts', ['alert_type', 'severity'], unique=False)
    op.create_index('ix_security_alerts_org_status_occurred', 'security_alerts', ['organization_id', 'status', 'occurred_at'], unique=False)
    op.create_table('visitor_kiosks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('access_point_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.String(length=255), nullable=False),
    sa.Column('allow_walk_in', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('require_host', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('require_liveness', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['access_point_id'], ['access_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_kiosks')
    op.drop_index('ix_security_alerts_org_status_occurred', table_name='security_alerts')
    op.drop_index('ix_security_alerts_alert_type_severity', table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index('ix_live_events_occurred_at_event_type', table_name='live_events')
    op.drop_table('live_events')
    op.drop_table('face_enrollment_images')
    op.drop_table('face_embeddings')
    op.drop_index('ix_attendance_anomalies_status_severity', table_name='attendance_anomalies')
    op.drop_index('ix_attendance_anomalies_employee_id_detected_at', table_name='attendance_anomalies')
    op.drop_index('ix_attendance_anomalies_anomaly_type_status', table_name='attendance_anomalies')
    op.drop_table('attendance_anomalies')
    op.drop_index('ix_access_events_access_point_id_occurred_at', table_name='access_events')
    op.drop_table('access_events')
    op.drop_index('ix_visitors_status_face_expires_at', table_name='visitors')
    op.drop_table('visitors')
    op.drop_index('ix_shift_assignments_employee_id_effective_from', table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_table('role_user')
    op.drop_index('ix_rfid_events_tapped_at_result', table_name='rfid_events')
    op.drop_index('ix_rfid_events_employee_id_tapped_at', table_name='rfid_events')
    op.drop_table('rfid_events')
    op.drop_index('ix_rfid_cards_uid_is_active', table_name='rfid_cards')
    op.drop_table('rfid_cards')
    op.drop_index('ix_recognition_events_recognized_at_result', table_name='recognition_events')
    op.drop_table('recognition_events')
    op.drop_table('leave_requests')
    op.drop_table('face_enrollment_sessions')
    op.drop_table('edge_devices')
    op.drop_index('ix_camera_health_logs_camera_id_recorded_at', table_name='camera_health_logs')
    op.drop_table('camera_health_logs')
    op.drop_index('ix_building_events_building_connector_id_created_at', table_name='building_events')
    op.drop_table('building_events')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_records_work_date_status', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('access_points')
    op.drop_index('ix_users_auth_provider_external_id', table_name='users')
    op.drop_table('users')
    op.drop_table('rfid_readers')
    op.drop_table('holidays')
    op.drop_index('ix_employees_organization_id_is_active', table_name='employees')
    op.drop_table('employees')
    op.drop_table('cameras')
    op.drop_table('building_connectors')
    op.drop_table('shifts')
    op.drop_table('locations')
    op.drop_table('departments')
    op.drop_table('role_permission')
    op.drop_table('branches')
    op.drop_table('attendance_policies')
    op.drop_table('roles')
    op.drop_index('ix_personal_access_tokens_tokenable', table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_table('permissions')
    op.drop_table('organizations')
    op.drop_index('ix_notifications_notifiable_type_notifiable_id', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
