"""Corrective data-model fixes (per-org employee code, holiday uniqueness, FK indexes)

Hand-authored (not autogenerated). Covers:
- employees.employee_code: was globally unique, so two tenants could not both
  have "EMP-001". Replace with a composite UNIQUE(organization_id, employee_code).
- holidays: the plain UNIQUE(organization_id, date, location_id) does not stop
  duplicate ORG-WIDE holidays because NULL location_id is distinct from NULL in
  Postgres. Replace with two partial unique indexes (per-location and org-wide).
- Missing indexes on hot FK columns: recognition_events.employee_id,
  leave_requests.employee_id, visitors.host_employee_id,
  attendance_records.location_id / camera_id.

PostgreSQL only. Verify on a real database (tests use SQLite/fakes):
  alembic upgrade head   then inspect the employees / holidays tables in psql.

Constraint names below assume PostgreSQL's default naming for the original
column-level unique (`employees_employee_code_key`) and the table
UniqueConstraint (`holidays_organization_id_date_location_id_key`). Adjust if
your database used different names.

Revision ID: e1f2a3b4c5d6
Revises: d0e1f2a3b4c5
Create Date: 2026-06-12

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e1f2a3b4c5d6"
down_revision: Union[str, None] = "d0e1f2a3b4c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── employees.employee_code: global unique -> per-org unique ──────────────
    op.drop_constraint("employees_employee_code_key", "employees", type_="unique")
    op.create_unique_constraint(
        "uq_employees_org_code", "employees", ["organization_id", "employee_code"]
    )

    # ── holidays: effective uniqueness for org-wide (NULL location) rows ──────
    op.drop_constraint(
        "holidays_organization_id_date_location_id_key", "holidays", type_="unique"
    )
    op.create_index(
        "uq_holidays_org_date_location",
        "holidays",
        ["organization_id", "date", "location_id"],
        unique=True,
        postgresql_where=sa.text("location_id IS NOT NULL"),
    )
    op.create_index(
        "uq_holidays_org_date_global",
        "holidays",
        ["organization_id", "date"],
        unique=True,
        postgresql_where=sa.text("location_id IS NULL"),
    )

    # ── Missing indexes on hot foreign-key columns ────────────────────────────
    op.create_index(
        "ix_recognition_events_employee_id", "recognition_events", ["employee_id"]
    )
    op.create_index("ix_leave_requests_employee_id", "leave_requests", ["employee_id"])
    op.create_index("ix_visitors_host_employee_id", "visitors", ["host_employee_id"])
    op.create_index(
        "ix_attendance_records_location_id", "attendance_records", ["location_id"]
    )
    op.create_index(
        "ix_attendance_records_camera_id", "attendance_records", ["camera_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_attendance_records_camera_id", table_name="attendance_records")
    op.drop_index("ix_attendance_records_location_id", table_name="attendance_records")
    op.drop_index("ix_visitors_host_employee_id", table_name="visitors")
    op.drop_index("ix_leave_requests_employee_id", table_name="leave_requests")
    op.drop_index("ix_recognition_events_employee_id", table_name="recognition_events")

    op.drop_index("uq_holidays_org_date_global", table_name="holidays")
    op.drop_index("uq_holidays_org_date_location", table_name="holidays")
    op.create_unique_constraint(
        "holidays_organization_id_date_location_id_key",
        "holidays",
        ["organization_id", "date", "location_id"],
    )

    op.drop_constraint("uq_employees_org_code", "employees", type_="unique")
    op.create_unique_constraint(
        "employees_employee_code_key", "employees", ["employee_code"]
    )
