"""Merge branches + departments into a self-referential organizations tree.

Hand-authored (not autogenerated). The ``organizations`` table becomes a tree:
a company *root* (``parent_id IS NULL``) is the tenant; ``branches`` and
``departments`` rows are migrated to descendant nodes. ``locations`` is kept
and repointed. Members (employees, users, locations) gain a single
``org_node_id`` replacing ``branch_id`` + ``department_id``.

Backfill precedence: department node if set, else branch node. The free-text
``employees.department`` label is left untouched. A ``_org_merge_audit`` table
preserves any branch link dropped when an employee's branch differed from its
department's branch (so the loss is recoverable post-hoc).

PostgreSQL only (like the rest of this chain — see e1f2a3b4c5d6). The data
transformation lives in ``backfill_org_tree`` using portable SQL so it can be
unit-tested against SQLite; the DDL below targets PostgreSQL.

FORWARD-ONLY: downgrade raises. branch/department identity and post-migration
reparenting cannot be losslessly reconstructed — restore from a backup instead.

Constraint name ``organizations_code_key`` assumes PostgreSQL's default naming
for the original column-level ``UNIQUE(code)`` (see 50fa64e85121).

Revision ID: g3b4c5d6e7f8
Revises: f2a3b4c5d6e7
Create Date: 2026-06-17
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "g3b4c5d6e7f8"
down_revision: Union[str, None] = "f2a3b4c5d6e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _assert_zero(conn, from_where: str) -> None:
    n = conn.execute(sa.text(f"SELECT count(*) FROM {from_where}")).scalar()
    if n:
        raise RuntimeError(
            f"org-tree migration integrity check failed: {n} row(s) in {from_where}"
        )


def backfill_org_tree(conn) -> None:
    """Populate the tree columns and repoint members. Portable (PG + SQLite).

    Assumes the new columns already exist on organizations/employees/users/
    locations, the old branches/departments tables still hold data, and the
    ``_org_merge_audit`` table exists. Does no NOT-NULL/constraint DDL.
    """
    # 0a. Cross-org dept->branch corruption: detach mismatched branch links
    #     (reparent the department to its own company root instead).
    conn.execute(
        sa.text(
            """
            UPDATE departments SET branch_id = NULL
            WHERE branch_id IS NOT NULL AND branch_id IN (
                SELECT b.id FROM branches b
                WHERE b.id = departments.branch_id
                  AND b.organization_id <> departments.organization_id
            )
            """
        )
    )

    # Anchor every existing organization as a company root.
    conn.execute(
        sa.text(
            """
            UPDATE organizations
            SET root_organization_id = id,
                node_type = 'company',
                depth = 0,
                path = '/' || CAST(id AS VARCHAR) || '/'
            WHERE parent_id IS NULL
            """
        )
    )

    roots = conn.execute(
        sa.text("SELECT id, code, path FROM organizations WHERE parent_id IS NULL")
    ).fetchall()
    root_path = {r.id: r.path for r in roots}
    used_codes: dict[int, set[str]] = {}
    for r in roots:
        used_codes.setdefault(r.id, set()).add(r.code)

    def unique_code(root_id: int, base: str, node_type: str, legacy_id: int) -> str:
        seen = used_codes.setdefault(root_id, set())
        cand = base
        if cand in seen:
            cand = f"{base}-{node_type}"
        if cand in seen:
            cand = f"{base}-{node_type}-{legacy_id}"
        suffix = 0
        while cand in seen:
            suffix += 1
            cand = f"{base}-{node_type}-{legacy_id}-{suffix}"
        seen.add(cand)
        return cand

    def insert_node(root_id, parent_id, parent_path, node_type, name, code, address, timezone, is_active, depth):
        # RETURNING id captures the new row deterministically — no dependency on
        # (root, code) being unique during the backfill window (a subtle code
        # collision would otherwise let the re-select pick the wrong row).
        new_id = conn.execute(
            sa.text(
                """
                INSERT INTO organizations
                    (name, code, parent_id, root_organization_id, node_type,
                     path, depth, timezone, address, is_active)
                VALUES (:name, :code, :parent, :root, :ntype, '', :depth, :tz, :addr, :active)
                RETURNING id
                """
            ),
            {
                "name": name, "code": code, "parent": parent_id, "root": root_id,
                "ntype": node_type, "depth": depth, "tz": timezone or "UTC",
                "addr": address, "active": is_active,
            },
        ).scalar()
        path = f"{parent_path}{new_id}/"
        conn.execute(
            sa.text("UPDATE organizations SET path = :p WHERE id = :id"),
            {"p": path, "id": new_id},
        )
        return new_id, path

    # Branch nodes (depth 1, parented to the company root).
    branch_map: dict[int, tuple[int, str]] = {}
    for b in conn.execute(
        sa.text(
            "SELECT id, organization_id, name, code, address, timezone, is_active FROM branches"
        )
    ).fetchall():
        root_id = b.organization_id
        code = unique_code(root_id, b.code, "branch", b.id)
        new_id, path = insert_node(
            root_id, root_id, root_path[root_id], "branch",
            b.name, code, b.address, b.timezone, b.is_active, 1,
        )
        branch_map[b.id] = (new_id, path)

    # Department nodes (under their branch node if any, else the company root).
    dept_map: dict[int, int] = {}
    for d in conn.execute(
        sa.text(
            "SELECT id, organization_id, branch_id, name, code, is_active FROM departments"
        )
    ).fetchall():
        root_id = d.organization_id
        if d.branch_id is not None and d.branch_id in branch_map:
            parent_id, parent_path = branch_map[d.branch_id]
            depth = 2
        else:
            parent_id, parent_path, depth = root_id, root_path[root_id], 1
        code = unique_code(root_id, d.code, "department", d.id)
        new_id, _ = insert_node(
            root_id, parent_id, parent_path, "department",
            d.name, code, None, "UTC", d.is_active, depth,
        )
        dept_map[d.id] = new_id

    # Audit: preserve branch links dropped by department-wins precedence.
    for member in ("employee", "user"):
        table = "employees" if member == "employee" else "users"
        conn.execute(
            sa.text(
                f"""
                INSERT INTO _org_merge_audit (member_type, member_id, branch_id, department_id)
                SELECT '{member}', m.id, m.branch_id, m.department_id
                FROM {table} m
                LEFT JOIN departments d ON d.id = m.department_id
                WHERE m.branch_id IS NOT NULL
                  AND m.department_id IS NOT NULL
                  AND (d.branch_id IS NULL OR d.branch_id <> m.branch_id)
                """
            )
        )

    # Id maps as temp tables, for set-based repointing.
    conn.execute(sa.text("CREATE TEMPORARY TABLE _branch_map (legacy_id INTEGER PRIMARY KEY, new_id INTEGER)"))
    conn.execute(sa.text("CREATE TEMPORARY TABLE _dept_map (legacy_id INTEGER PRIMARY KEY, new_id INTEGER)"))
    if branch_map:
        conn.execute(
            sa.text("INSERT INTO _branch_map (legacy_id, new_id) VALUES (:l, :n)"),
            [{"l": k, "n": v[0]} for k, v in branch_map.items()],
        )
    if dept_map:
        conn.execute(
            sa.text("INSERT INTO _dept_map (legacy_id, new_id) VALUES (:l, :n)"),
            [{"l": k, "n": v} for k, v in dept_map.items()],
        )

    # Repoint members: department wins, else branch.
    for table in ("employees", "users"):
        conn.execute(
            sa.text(
                f"""
                UPDATE {table} SET org_node_id =
                    (SELECT new_id FROM _dept_map WHERE legacy_id = {table}.department_id)
                WHERE department_id IS NOT NULL
                """
            )
        )
        conn.execute(
            sa.text(
                f"""
                UPDATE {table} SET org_node_id =
                    (SELECT new_id FROM _branch_map WHERE legacy_id = {table}.branch_id)
                WHERE org_node_id IS NULL AND branch_id IS NOT NULL
                """
            )
        )
    # Root-less guard: a user with no tenant must not carry a scope node.
    conn.execute(sa.text("UPDATE users SET org_node_id = NULL WHERE organization_id IS NULL"))

    # Locations only ever pointed at a branch.
    conn.execute(
        sa.text(
            """
            UPDATE locations SET org_node_id =
                (SELECT new_id FROM _branch_map WHERE legacy_id = locations.branch_id)
            WHERE branch_id IS NOT NULL
            """
        )
    )

    conn.execute(sa.text("DROP TABLE _branch_map"))
    conn.execute(sa.text("DROP TABLE _dept_map"))


def upgrade() -> None:
    bind = op.get_bind()

    # ── Additive columns ──────────────────────────────────────────────────────
    op.add_column("organizations", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.add_column("organizations", sa.Column("root_organization_id", sa.Integer(), nullable=True))
    op.add_column(
        "organizations",
        sa.Column("node_type", sa.String(length=32), server_default="company", nullable=False),
    )
    op.add_column("organizations", sa.Column("path", sa.String(length=512), nullable=True))
    op.add_column("organizations", sa.Column("depth", sa.Integer(), server_default="0", nullable=False))
    op.add_column("organizations", sa.Column("address", sa.String(length=255), nullable=True))
    op.add_column("employees", sa.Column("org_node_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("org_node_id", sa.Integer(), nullable=True))
    op.add_column("locations", sa.Column("org_node_id", sa.Integer(), nullable=True))

    op.create_table(
        "_org_merge_audit",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("member_type", sa.String(length=16), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("branch_id", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
    )

    # ── Data backfill ─────────────────────────────────────────────────────────
    backfill_org_tree(bind)

    _assert_zero(bind, "organizations WHERE root_organization_id IS NULL")
    _assert_zero(bind, "organizations WHERE path IS NULL")

    # ── Finalize columns / constraints / indexes ──────────────────────────────
    op.alter_column("organizations", "root_organization_id", nullable=False)
    op.alter_column("organizations", "path", nullable=False)

    op.create_foreign_key(
        "fk_org_parent_id", "organizations", "organizations",
        ["parent_id"], ["id"], ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_org_root_organization_id", "organizations", "organizations",
        ["root_organization_id"], ["id"], ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_employees_org_node_id", "employees", "organizations",
        ["org_node_id"], ["id"], ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_users_org_node_id", "users", "organizations",
        ["org_node_id"], ["id"], ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_locations_org_node_id", "locations", "organizations",
        ["org_node_id"], ["id"], ondelete="RESTRICT",
    )

    # Company code was globally unique; now codes are unique within a company.
    op.drop_constraint("organizations_code_key", "organizations", type_="unique")
    op.create_unique_constraint(
        "uq_org_root_code", "organizations", ["root_organization_id", "code"]
    )

    op.create_index("ix_org_root_active", "organizations", ["root_organization_id", "is_active"])
    op.create_index("ix_org_parent", "organizations", ["parent_id"])
    # text_pattern_ops keeps the sub-tree prefix LIKE sargable on PostgreSQL.
    op.create_index(
        "ix_org_path", "organizations", ["path"], postgresql_ops={"path": "text_pattern_ops"}
    )
    op.create_index("ix_employees_org_node", "employees", ["org_node_id"])
    op.create_index("ix_users_org_node", "users", ["org_node_id"])
    op.create_index("ix_locations_org_node", "locations", ["org_node_id"])

    # ── Retire legacy columns + tables ─────────────────────────────────────────
    op.drop_column("employees", "branch_id")
    op.drop_column("employees", "department_id")
    op.drop_column("users", "branch_id")
    op.drop_column("users", "department_id")
    op.drop_column("locations", "branch_id")
    op.drop_table("departments")
    op.drop_table("branches")

    # ── Final integrity: no member assigned to a node in a different tenant ────
    _assert_zero(
        bind,
        "employees e JOIN organizations o ON o.id = e.org_node_id "
        "WHERE o.root_organization_id <> e.organization_id",
    )
    _assert_zero(
        bind,
        "users u JOIN organizations o ON o.id = u.org_node_id "
        "WHERE u.organization_id IS NOT NULL AND o.root_organization_id <> u.organization_id",
    )


def downgrade() -> None:
    raise NotImplementedError(
        "Org-tree merge is forward-only: branch/department identity and "
        "post-migration reparenting cannot be losslessly reconstructed. "
        "Restore from a pre-migration backup to roll back."
    )
