/**
 * A curated, dependency-free emoji dataset for the chat picker. Each entry pairs
 * an emoji with a short keyword string for search. Grouped into the standard
 * Unicode categories; not exhaustive, but a professional working set.
 */
export interface EmojiEntry {
  e: string
  k: string
}

export interface EmojiCategory {
  id: string
  label: string
  /** Glyph shown on the category tab. */
  icon: string
  emojis: EmojiEntry[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    label: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { e: '😀', k: 'grin happy smile' },
      { e: '😁', k: 'beam grin happy' },
      { e: '😂', k: 'joy laugh tears lol' },
      { e: '🤣', k: 'rofl laugh rolling' },
      { e: '😃', k: 'smile happy' },
      { e: '😄', k: 'smile happy laugh' },
      { e: '😅', k: 'sweat smile nervous' },
      { e: '😆', k: 'laugh satisfied' },
      { e: '😉', k: 'wink' },
      { e: '😊', k: 'blush smile happy' },
      { e: '🙂', k: 'slight smile' },
      { e: '🙃', k: 'upside down silly' },
      { e: '😋', k: 'yum tasty tongue' },
      { e: '😌', k: 'relieved calm' },
      { e: '😍', k: 'heart eyes love' },
      { e: '🥰', k: 'love hearts adore' },
      { e: '😘', k: 'kiss blow' },
      { e: '😗', k: 'kiss' },
      { e: '😎', k: 'cool sunglasses' },
      { e: '🤩', k: 'star struck excited wow' },
      { e: '🥳', k: 'party celebrate' },
      { e: '😏', k: 'smirk' },
      { e: '😒', k: 'unamused meh' },
      { e: '😞', k: 'disappointed sad' },
      { e: '😔', k: 'pensive sad' },
      { e: '😟', k: 'worried' },
      { e: '😕', k: 'confused' },
      { e: '🙁', k: 'frown sad' },
      { e: '😣', k: 'persevere' },
      { e: '😖', k: 'confounded' },
      { e: '😫', k: 'tired' },
      { e: '😩', k: 'weary' },
      { e: '🥺', k: 'pleading puppy eyes' },
      { e: '😢', k: 'cry sad tear' },
      { e: '😭', k: 'sob cry loud' },
      { e: '😤', k: 'triumph steam huff' },
      { e: '😠', k: 'angry' },
      { e: '😡', k: 'rage mad angry' },
      { e: '🤬', k: 'swear curse angry' },
      { e: '🤯', k: 'mind blown shock' },
      { e: '😳', k: 'flushed embarrassed' },
      { e: '🥵', k: 'hot heat' },
      { e: '🥶', k: 'cold freeze' },
      { e: '😱', k: 'scream shock fear' },
      { e: '😨', k: 'fearful' },
      { e: '😰', k: 'anxious sweat' },
      { e: '😥', k: 'sad relieved' },
      { e: '🤔', k: 'thinking hmm' },
      { e: '🤗', k: 'hug' },
      { e: '🤭', k: 'giggle oops' },
      { e: '🤫', k: 'shush quiet' },
      { e: '🤥', k: 'lying liar' },
      { e: '😶', k: 'no mouth speechless' },
      { e: '😐', k: 'neutral' },
      { e: '😑', k: 'expressionless' },
      { e: '😬', k: 'grimace awkward' },
      { e: '🙄', k: 'eye roll' },
      { e: '😯', k: 'hushed surprised' },
      { e: '😴', k: 'sleep zzz' },
      { e: '🤤', k: 'drool' },
      { e: '😪', k: 'sleepy' },
      { e: '😷', k: 'mask sick' },
      { e: '🤒', k: 'sick thermometer' },
      { e: '🤕', k: 'hurt bandage' },
      { e: '🤧', k: 'sneeze' },
      { e: '🥴', k: 'woozy dizzy' },
      { e: '😵', k: 'dizzy ko' },
      { e: '🤠', k: 'cowboy' },
      { e: '😈', k: 'devil mischief' },
      { e: '👿', k: 'angry devil' },
      { e: '👻', k: 'ghost boo' },
      { e: '💀', k: 'skull dead' },
      { e: '🤡', k: 'clown' },
      { e: '💩', k: 'poop' },
    ],
  },
  {
    id: 'people',
    label: 'People & Body',
    icon: '👍',
    emojis: [
      { e: '👍', k: 'thumbs up like yes' },
      { e: '👎', k: 'thumbs down dislike no' },
      { e: '👏', k: 'clap applause' },
      { e: '🙌', k: 'raise hands praise' },
      { e: '👐', k: 'open hands' },
      { e: '🤲', k: 'palms up' },
      { e: '🤝', k: 'handshake deal' },
      { e: '🙏', k: 'pray thanks please' },
      { e: '✌️', k: 'peace victory' },
      { e: '🤞', k: 'fingers crossed luck' },
      { e: '🤟', k: 'love you' },
      { e: '🤘', k: 'rock horns' },
      { e: '👌', k: 'ok perfect' },
      { e: '🤌', k: 'pinched italian' },
      { e: '👈', k: 'point left' },
      { e: '👉', k: 'point right' },
      { e: '👆', k: 'point up' },
      { e: '👇', k: 'point down' },
      { e: '☝️', k: 'index up' },
      { e: '✋', k: 'raised hand stop' },
      { e: '🤚', k: 'back of hand' },
      { e: '🖐️', k: 'hand fingers' },
      { e: '🖖', k: 'vulcan spock' },
      { e: '👋', k: 'wave hi bye hello' },
      { e: '🤙', k: 'call me shaka' },
      { e: '💪', k: 'muscle strong flex' },
      { e: '🦾', k: 'mechanical arm strong' },
      { e: '✍️', k: 'writing' },
      { e: '👀', k: 'eyes look' },
      { e: '👁️', k: 'eye' },
      { e: '🧠', k: 'brain smart' },
      { e: '👄', k: 'mouth lips' },
      { e: '❤️', k: 'heart love red' },
      { e: '🧡', k: 'orange heart' },
      { e: '💛', k: 'yellow heart' },
      { e: '💚', k: 'green heart' },
      { e: '💙', k: 'blue heart' },
      { e: '💜', k: 'purple heart' },
      { e: '🖤', k: 'black heart' },
      { e: '🤍', k: 'white heart' },
      { e: '💔', k: 'broken heart' },
      { e: '❤️‍🔥', k: 'heart fire' },
      { e: '💕', k: 'two hearts love' },
      { e: '💞', k: 'revolving hearts' },
      { e: '💓', k: 'beating heart' },
      { e: '💗', k: 'growing heart' },
      { e: '💖', k: 'sparkling heart' },
      { e: '💘', k: 'heart arrow cupid' },
      { e: '💝', k: 'heart gift' },
      { e: '💯', k: 'hundred perfect score' },
    ],
  },
  {
    id: 'nature',
    label: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { e: '🐶', k: 'dog puppy' },
      { e: '🐱', k: 'cat' },
      { e: '🐭', k: 'mouse' },
      { e: '🐹', k: 'hamster' },
      { e: '🐰', k: 'rabbit bunny' },
      { e: '🦊', k: 'fox' },
      { e: '🐻', k: 'bear' },
      { e: '🐼', k: 'panda' },
      { e: '🐨', k: 'koala' },
      { e: '🐯', k: 'tiger' },
      { e: '🦁', k: 'lion' },
      { e: '🐮', k: 'cow' },
      { e: '🐷', k: 'pig' },
      { e: '🐸', k: 'frog' },
      { e: '🐵', k: 'monkey' },
      { e: '🐔', k: 'chicken' },
      { e: '🐧', k: 'penguin' },
      { e: '🐦', k: 'bird' },
      { e: '🦄', k: 'unicorn' },
      { e: '🐝', k: 'bee' },
      { e: '🦋', k: 'butterfly' },
      { e: '🐢', k: 'turtle' },
      { e: '🐙', k: 'octopus' },
      { e: '🐳', k: 'whale' },
      { e: '🐬', k: 'dolphin' },
      { e: '🐟', k: 'fish' },
      { e: '🦈', k: 'shark' },
      { e: '🌸', k: 'blossom flower' },
      { e: '🌹', k: 'rose flower' },
      { e: '🌻', k: 'sunflower' },
      { e: '🌷', k: 'tulip flower' },
      { e: '🌲', k: 'tree evergreen' },
      { e: '🌴', k: 'palm tree' },
      { e: '🌵', k: 'cactus' },
      { e: '🍀', k: 'clover luck' },
      { e: '🍁', k: 'maple leaf' },
      { e: '⭐', k: 'star' },
      { e: '🌟', k: 'glowing star' },
      { e: '✨', k: 'sparkles' },
      { e: '⚡', k: 'lightning bolt' },
      { e: '🔥', k: 'fire lit hot' },
      { e: '🌈', k: 'rainbow' },
      { e: '☀️', k: 'sun sunny' },
      { e: '⛅', k: 'cloud sun' },
      { e: '☁️', k: 'cloud' },
      { e: '❄️', k: 'snowflake cold' },
      { e: '🌊', k: 'wave water ocean' },
      { e: '💧', k: 'droplet water' },
      { e: '🌙', k: 'moon night' },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { e: '🍏', k: 'green apple' },
      { e: '🍎', k: 'apple' },
      { e: '🍊', k: 'orange' },
      { e: '🍋', k: 'lemon' },
      { e: '🍌', k: 'banana' },
      { e: '🍉', k: 'watermelon' },
      { e: '🍇', k: 'grapes' },
      { e: '🍓', k: 'strawberry' },
      { e: '🫐', k: 'blueberries' },
      { e: '🍒', k: 'cherries' },
      { e: '🍑', k: 'peach' },
      { e: '🥭', k: 'mango' },
      { e: '🍍', k: 'pineapple' },
      { e: '🥥', k: 'coconut' },
      { e: '🥝', k: 'kiwi' },
      { e: '🍅', k: 'tomato' },
      { e: '🥑', k: 'avocado' },
      { e: '🌽', k: 'corn' },
      { e: '🥕', k: 'carrot' },
      { e: '🍔', k: 'burger' },
      { e: '🍟', k: 'fries' },
      { e: '🍕', k: 'pizza' },
      { e: '🌭', k: 'hotdog' },
      { e: '🌮', k: 'taco' },
      { e: '🌯', k: 'burrito' },
      { e: '🍜', k: 'noodles ramen' },
      { e: '🍲', k: 'stew pot' },
      { e: '🍣', k: 'sushi' },
      { e: '🍱', k: 'bento' },
      { e: '🍚', k: 'rice' },
      { e: '🍞', k: 'bread' },
      { e: '🧀', k: 'cheese' },
      { e: '🥚', k: 'egg' },
      { e: '🍳', k: 'fried egg cooking' },
      { e: '🥓', k: 'bacon' },
      { e: '🍰', k: 'cake slice' },
      { e: '🎂', k: 'birthday cake' },
      { e: '🧁', k: 'cupcake' },
      { e: '🍩', k: 'donut' },
      { e: '🍪', k: 'cookie' },
      { e: '🍫', k: 'chocolate' },
      { e: '🍬', k: 'candy' },
      { e: '🍦', k: 'ice cream' },
      { e: '☕', k: 'coffee tea' },
      { e: '🍵', k: 'tea green' },
      { e: '🥤', k: 'soda drink cup' },
      { e: '🍺', k: 'beer' },
      { e: '🍻', k: 'beers cheers' },
      { e: '🍷', k: 'wine' },
      { e: '🥂', k: 'champagne cheers toast' },
    ],
  },
  {
    id: 'activities',
    label: 'Activities',
    icon: '⚽',
    emojis: [
      { e: '⚽', k: 'soccer football' },
      { e: '🏀', k: 'basketball' },
      { e: '🏈', k: 'football american' },
      { e: '⚾', k: 'baseball' },
      { e: '🎾', k: 'tennis' },
      { e: '🏐', k: 'volleyball' },
      { e: '🏉', k: 'rugby' },
      { e: '🎱', k: 'pool 8 ball' },
      { e: '🏓', k: 'ping pong' },
      { e: '🏸', k: 'badminton' },
      { e: '🥅', k: 'goal net' },
      { e: '⛳', k: 'golf' },
      { e: '🎯', k: 'dart target bullseye' },
      { e: '🎮', k: 'game controller' },
      { e: '🕹️', k: 'joystick' },
      { e: '🎲', k: 'dice' },
      { e: '♟️', k: 'chess' },
      { e: '🧩', k: 'puzzle' },
      { e: '🎨', k: 'art paint' },
      { e: '🎭', k: 'theater drama' },
      { e: '🎤', k: 'mic sing' },
      { e: '🎧', k: 'headphones music' },
      { e: '🎸', k: 'guitar' },
      { e: '🎹', k: 'piano keyboard' },
      { e: '🥁', k: 'drum' },
      { e: '🎺', k: 'trumpet' },
      { e: '🏆', k: 'trophy win' },
      { e: '🥇', k: 'gold medal first' },
      { e: '🥈', k: 'silver medal second' },
      { e: '🥉', k: 'bronze medal third' },
      { e: '🏅', k: 'medal' },
      { e: '🎖️', k: 'military medal' },
      { e: '🎉', k: 'party tada celebrate' },
      { e: '🎊', k: 'confetti' },
      { e: '🎈', k: 'balloon' },
      { e: '🎁', k: 'gift present' },
      { e: '🎀', k: 'ribbon bow' },
      { e: '🎇', k: 'sparkler fireworks' },
      { e: '🎆', k: 'fireworks' },
      { e: '🚴', k: 'cycling bike' },
      { e: '🏃', k: 'running run' },
      { e: '🏊', k: 'swimming swim' },
      { e: '🧗', k: 'climbing' },
      { e: '⛷️', k: 'ski' },
      { e: '🏂', k: 'snowboard' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & Places',
    icon: '🚗',
    emojis: [
      { e: '🚗', k: 'car' },
      { e: '🚕', k: 'taxi' },
      { e: '🚙', k: 'suv car' },
      { e: '🚌', k: 'bus' },
      { e: '🏎️', k: 'race car fast' },
      { e: '🚓', k: 'police car' },
      { e: '🚑', k: 'ambulance' },
      { e: '🚒', k: 'fire truck' },
      { e: '🚜', k: 'tractor' },
      { e: '🛵', k: 'scooter' },
      { e: '🏍️', k: 'motorcycle' },
      { e: '🚲', k: 'bicycle bike' },
      { e: '✈️', k: 'plane flight travel' },
      { e: '🚀', k: 'rocket launch' },
      { e: '🛸', k: 'ufo' },
      { e: '🚁', k: 'helicopter' },
      { e: '⛵', k: 'sailboat' },
      { e: '🚤', k: 'speedboat' },
      { e: '🛳️', k: 'ship cruise' },
      { e: '🚂', k: 'train' },
      { e: '🚆', k: 'train' },
      { e: '🚇', k: 'metro subway' },
      { e: '🗺️', k: 'map' },
      { e: '🧭', k: 'compass' },
      { e: '🗽', k: 'statue liberty' },
      { e: '🗼', k: 'tower tokyo' },
      { e: '🏰', k: 'castle' },
      { e: '🏯', k: 'japanese castle' },
      { e: '🏟️', k: 'stadium' },
      { e: '🎡', k: 'ferris wheel' },
      { e: '🎢', k: 'roller coaster' },
      { e: '🏖️', k: 'beach' },
      { e: '🏝️', k: 'island' },
      { e: '⛰️', k: 'mountain' },
      { e: '🌋', k: 'volcano' },
      { e: '🏕️', k: 'camping tent' },
      { e: '🏠', k: 'house home' },
      { e: '🏢', k: 'office building' },
      { e: '🏥', k: 'hospital' },
      { e: '🏦', k: 'bank' },
      { e: '🏫', k: 'school' },
      { e: '🌃', k: 'night city' },
      { e: '🌆', k: 'city sunset' },
      { e: '🌉', k: 'bridge night' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    icon: '💡',
    emojis: [
      { e: '⌚', k: 'watch time' },
      { e: '📱', k: 'phone mobile' },
      { e: '💻', k: 'laptop computer' },
      { e: '🖥️', k: 'desktop computer' },
      { e: '⌨️', k: 'keyboard' },
      { e: '🖱️', k: 'mouse' },
      { e: '🖨️', k: 'printer' },
      { e: '📷', k: 'camera photo' },
      { e: '📸', k: 'camera flash' },
      { e: '🎥', k: 'movie camera video' },
      { e: '📹', k: 'video camera' },
      { e: '📞', k: 'phone call telephone' },
      { e: '☎️', k: 'telephone' },
      { e: '📟', k: 'pager' },
      { e: '📺', k: 'tv television' },
      { e: '📻', k: 'radio' },
      { e: '🔋', k: 'battery' },
      { e: '🔌', k: 'plug power' },
      { e: '💡', k: 'idea light bulb' },
      { e: '🔦', k: 'flashlight torch' },
      { e: '🕯️', k: 'candle' },
      { e: '💰', k: 'money bag' },
      { e: '💵', k: 'dollar cash money' },
      { e: '💳', k: 'credit card' },
      { e: '💎', k: 'gem diamond' },
      { e: '⚖️', k: 'scales balance justice' },
      { e: '🔧', k: 'wrench tool fix' },
      { e: '🔨', k: 'hammer' },
      { e: '🛠️', k: 'tools' },
      { e: '⚙️', k: 'gear settings' },
      { e: '🧲', k: 'magnet' },
      { e: '🔒', k: 'lock secure' },
      { e: '🔑', k: 'key' },
      { e: '📌', k: 'pin' },
      { e: '📎', k: 'paperclip attach' },
      { e: '✂️', k: 'scissors cut' },
      { e: '📝', k: 'memo note write' },
      { e: '📄', k: 'document page' },
      { e: '📁', k: 'folder' },
      { e: '📅', k: 'calendar date' },
      { e: '📊', k: 'bar chart' },
      { e: '📈', k: 'chart up growth' },
      { e: '📉', k: 'chart down' },
      { e: '📚', k: 'books' },
      { e: '✏️', k: 'pencil' },
      { e: '🖊️', k: 'pen' },
      { e: '💼', k: 'briefcase work' },
      { e: '🔭', k: 'telescope' },
      { e: '🔬', k: 'microscope' },
      { e: '💊', k: 'pill medicine' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    icon: '✅',
    emojis: [
      { e: '✅', k: 'check done yes ok' },
      { e: '☑️', k: 'checkbox done' },
      { e: '✔️', k: 'check mark' },
      { e: '❌', k: 'cross no wrong x' },
      { e: '❎', k: 'no cross' },
      { e: '➕', k: 'plus add' },
      { e: '➖', k: 'minus subtract' },
      { e: '➗', k: 'divide' },
      { e: '✖️', k: 'multiply x' },
      { e: '❓', k: 'question' },
      { e: '❗', k: 'exclamation' },
      { e: '‼️', k: 'double exclamation' },
      { e: '⁉️', k: 'interrobang' },
      { e: '💲', k: 'dollar sign' },
      { e: '💱', k: 'currency exchange' },
      { e: '♻️', k: 'recycle' },
      { e: '⚠️', k: 'warning caution' },
      { e: '🚫', k: 'no forbidden' },
      { e: '🔞', k: 'no under 18' },
      { e: '📵', k: 'no phones' },
      { e: '🔅', k: 'dim brightness' },
      { e: '🔆', k: 'bright brightness' },
      { e: '✳️', k: 'asterisk' },
      { e: '❇️', k: 'sparkle' },
      { e: '💠', k: 'diamond shape' },
      { e: '🔷', k: 'blue diamond' },
      { e: '🔶', k: 'orange diamond' },
      { e: '🔵', k: 'blue circle' },
      { e: '🟢', k: 'green circle' },
      { e: '🔴', k: 'red circle' },
      { e: '🟡', k: 'yellow circle' },
      { e: '🟠', k: 'orange circle' },
      { e: '🟣', k: 'purple circle' },
      { e: '⚫', k: 'black circle' },
      { e: '⚪', k: 'white circle' },
      { e: '🔺', k: 'red triangle up' },
      { e: '🔻', k: 'red triangle down' },
      { e: '💤', k: 'sleep zzz' },
      { e: '🔔', k: 'bell notification' },
      { e: '🔕', k: 'mute bell off' },
      { e: '🎵', k: 'music note' },
      { e: '🎶', k: 'music notes' },
      { e: '➡️', k: 'arrow right' },
      { e: '⬅️', k: 'arrow left' },
      { e: '⬆️', k: 'arrow up' },
      { e: '⬇️', k: 'arrow down' },
      { e: '🔁', k: 'repeat loop' },
      { e: '🔄', k: 'refresh sync' },
      { e: '▶️', k: 'play' },
      { e: '⏸️', k: 'pause' },
    ],
  },
]
